name: ci-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: bdockerimg/quicklisp
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Coalton
        run: |
          set -ex
          apt-get install git
          git clone \
            https://github.com/coalton-lang/coalton.git \
            /root/quicklisp/local-projects/coalton
      - name: Run Tests
        run: |
          set -ex
          sbcl --disable-debugger \
               --load /root/quicklisp/setup.lisp \
               --eval '(ql:update-all-dists)' \
               --load coalton-threads.asd \
               --eval '(ql:quickload :coalton-threads/test)' \
               --eval '(asdf:test-system :coalton-threads/test)' \
               --eval '(quit)'